name: 5 Keys to Unlock Autoimmune Shackles.
title: 5 Keys to Unlock Autoimmune Shackles.
tagline: Harnessing the Power of Microbiome and Digestive Health as a Holistic Solution to Rheumatoid Arthritis, Lupus, and Crohn’s Disease.
description: Harnessing the Power of Microbiome and Digestive Health as a Holistic Solution to Rheumatoid Arthritis, Lupus, and Crohn’s Disease.
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
commonmark:
  extensions:
    - autolink
redcarpet:
  extensions:
    - autolink
