name: 5 Keys to Unlock Autoimmune Shackles.
title: 5 Keys to Unlock Autoimmune Shackles.
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
commonmark:
  extensions:
    - autolink
redcarpet:
  extensions:
    - autolink
